/** Model writing guidance; links remain prose and do not create database relations. */
export const MEMORY_NOTE_WRITING_GUIDELINES = [
	"Give each decision note a short title naming the specific decision and current outcome or revision, preferably in the user's language. Avoid batch-topic lists that hide the key change. Use category=decision for decisions and their revisions; distinguish proposals from approved decisions.",
	"For the same decision in the same scope, find and reuse its stable note_id rather than creating a new checkpoint note each window. Put the current supported decision first, followed by the relevant old decision -> new decision, scope, conditions, reason when known, and evidence. Keep unrelated decisions separate. Upsert replaces the whole body: read it when needed and preserve still-valid details and metadata. Existing source Entry IDs are retained by the tool; provide only new, actual source IDs. Do not rewrite unaffected notes or mark an older decision obsolete merely because time passed.",
	"For a durable decision or constraint that governs future work, preserve its concrete, testable behavior, applicable conditions and boundaries, relevant edge cases or quantities, and any explicitly forbidden approach. Record acceptance checks still needed as unverified, not passed. Distinguish user-approved requirements from proposals and implementation observations; do not invent missing requirements or duplicate routine Workflow progress in Notes.",
	"For work spanning multiple Workflows or user-requested stages, keep one compact decision or constraint Note per stable topic when a later Workflow must retain an earlier user requirement, boundary condition or regression guard that the current Workflow Projection will not carry and the Workspace cannot reliably reconstruct. Reuse the same note_id and update it only when that cross-Workflow contract is missing or changed. Do not create one Note per stage or store progress, files, verification state or next actions.",
	"When an analysis introduces an actionable proposal that a future turn may implement, preserve the proposed behavior and its conditions or prohibited shortcuts in a Note even if approval is still pending. Label it as a proposal, not a user requirement, and separate it from observed current behavior; do not reduce it to the defect or a vague reminder to fix it later. When the user approves, rejects or revises that proposal, update the same scoped note with the new decision status and still-valid behavior in that turn. Do not save routine suggestions that will not constrain future work.",
	"Default to zero Note writes when a turn only implements behavior that existing Notes already preserve. Save an open question only for an unresolved external decision or missing evidence whose answer can change future action, and only when the user requested it, it blocks the next action, or future work must resolve it. Verification not run, remaining files or stages, next action, implementation completion or readiness, and test or acceptance status are Workflow facts, never open questions. Do not update an open question merely because an implementation stage completed; update it only when the unresolved choice or evidence changes or becomes resolved, or when the user changes its priority. Do not save speculative behavior for unsupported inputs or edge cases merely because the requirements are silent.",
	"Do not save a discovery that can be recovered from the current workspace, including current code, symbols, files, configuration or repository state. Read the workspace when that information is needed; reserve discovery Notes for durable findings that the current workspace cannot reconstruct.",
	"When several proposals are approved together, revise each existing note_id separately with that proposal's own approved behavior and boundaries. Do not copy a combined approval, implementation report, or the same body into multiple decision Notes. Record implementation and verification progress in Workflow, not as replacement decision bodies.",
	"Include short search aliases in the user's language, including relevant Chinese terms for Chinese conversations, alongside useful technical/English terms and common wording variants. Keywords are literal search aids, not inferred facts; stay within the existing keyword limits. Record actual known original message Entry IDs in source_entry_ids and identify which decision each supports in the body. Note IDs and source line numbers are not original message Entry IDs. If unavailable, leave sources empty/null rather than querying History solely to add provenance or inventing IDs.",
	"If a revision must live in a separate note, first save it successfully and obtain its actual note_id. Then update the old note's title and affected passage to mark that decision superseded and point to the new note_id for notes read; the new note should identify the old note and changed scope. Preserve unrelated valid content and historical reasons in both. A Note link belongs in the body, not source_entry_ids. Do not archive the old note just to hide a conflict. These writes are separate: if linking fails, report the incomplete link rather than claiming both records are synchronized.",
] as const;
