/** Shared guidance for Notes and History; retrieval remains model-directed. */
export const WORKFLOW_PROJECTION_RETRIEVAL_GUIDELINE =
	"At a new context window, use the visible Workflow Projection for task state and receipts, Workspace/diff for current code, Notes for durable design semantics, and History only for exact unavailable prior evidence. Do not query Notes or History merely to reconfirm a receipt or rediscover current repository state.";

export const WORKFLOW_RECEIPT_RETRIEVAL_GUIDELINE =
	"Workflow Operation Receipts are authoritative for whether an explicitly marked one-shot operation or verification call already ran. Do not query Notes or History merely to reconfirm a recorded execution, and do not repeat the call solely to recover its result. Use the receipt's short result first; query History for the specific tool result only when exact unavailable output is required for the current action. Notes may preserve design meaning, but must not override a host-observed receipt.";

export const MEMORY_REVISION_GUIDELINE =
	"When asked for a final, later or current decision, establish the requested time scope for that specific decision. An early decision alone is insufficient if later discussion is in scope. Read relevant later Notes or search for subsequent changes; use History when Notes do not establish the outcome. A note's update time and words like current/final describe that note's checkpoint, not every fact's validity. Silence in a newer note does not confirm or cancel an older decision, and age alone does not make a decision obsolete. A complete visible Active Note body is sufficient for an exact rule when no conflict, missing detail, requested quotation or explicit evidence requirement remains: do not query History merely to reconfirm it or obtain provenance/source Entry IDs. Stop when evidence covers the requested period and resolves relevant revisions; otherwise report the remaining uncertainty. Ordinary facts and decisions already adequately supported require no extra lookup.";

export const MEMORY_TARGETED_SEARCH_GUIDELINE =
	"Search for the specific unresolved decision, condition or relationship, not just a broad topic noun. Notes and History search use literal substrings: choose short distinctive terms found in the question or visible records, try wording/spacing variants separately, and do not assume semantic or Boolean query support. For user decisions, prefer role=user in History; read surrounding context when a brief approval needs its proposal. Use returned source IDs and window order to inspect relevant later discussion, including intermediate windows; the first hit is not necessarily the final decision. Read enough context to distinguish proposals, approvals and revisions. Do not treat an empty or truncated keyword search as proof that no revision exists, or combine unrelated decisions merely because they share vocabulary.";
